language: perl
matrix:
    fast_finish: true
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - cpanm -qn DBI
    - cpanm -qn DBD::Pg
    - cpanm -qn AnyEvent
    - cpanm -qn POSIX
    - cpanm -qn Getopt::Long
    - cpanm -qn Pod::Usage
    - cpanm -qn Time::HiRes
    - cpanm -qn Test::Requires::Git
    - cpanm -qn Devel::Cover::Report::Codecov

script:
    perl Makefile.PL && make test && cover -test -report codecov

notifications:
  email:
    - ebow@binary.com
