language: perl
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"

before_install:
    - cpanm DBI
    - cpanm DBD::Pg
    - cpanm AnyEvent
    - cpanm POSIX
    - cpanm Getopt::Long
    - cpanm Pod::Usage
    - cpanm Time::HiRes

notifications:
  email:
    - ebow@binary.com
